channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1
- pip:
  - mlflow==2.21.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==5.9.8
  - scikit-learn==1.5.2
  - scipy==1.15.1
name: mlflow-env
